### ISSUE TITLE
Closing parentheses placement does not match Kotlin style guide

### ISSUE THREAD

**Issue by sgrimm** [facebookincubator/ktfmt#10]
I'm not sure if this is on purpose or merely a side effect of the google-java-format-based implementation, but ktfmt's placement of closing parentheses on expressions or argument lists that it splits across multiple lines doesn't match the placement in the official Kotlin style guide, which says there should be a line break. It seems to be a general rule there, but backed by some specific examples:

* [Class headers](https://kotlinlang.org/docs/reference/coding-conventions.html#class-header-formatting)
* [Control flow statements](https://kotlinlang.org/docs/reference/coding-conventions.html#formatting-control-flow-statements)
* [Method calls](https://kotlinlang.org/docs/reference/coding-conventions.html#method-call-formatting)

Obviously ktfmt is under no obligation to strictly follow that style guide; if that's on purpose please close this and I'll avoid filing any similar issues in the future.

**Comment by sgrimm** [comment]
Simple example:

```kotlin
fun splitArgumentListTest(arg1: String, arg2: String, arg3: String, arg4: String, arg5: String, arg6: String) {
  //
}
```

ktfmt formats this as:

```kotlin
fun splitArgumentListTest(
    arg1: String, arg2: String, arg3: String, arg4: String, arg5: String, arg6: String) {
  //
}
```

whereas the style guide would suggest:

```kotlin
fun splitArgumentListTest(
    arg1: String, arg2: String, arg3: String, arg4: String, arg5: String, arg6: String
) {
  //
}
```

The style guide, unfortunately, doesn't lay down a hard-and-fast rule about keeping arguments on one line vs. splitting them; it says "closely related" arguments should be on the same line but of course that's impossible for an automated tool to determine.

**Comment by cgrushko** [comment]
We do move the closing parenthesis to the next line when there's a type (https://github.com/facebookincubator/ktfmt/blob/fb81db8c849d002c2ae9846eba4607c7d2f2cef6/core/src/test/java/com/facebook/ktfmt/FormatterKtTest.kt#L561), so maybe for consistency's sake we should also do this in this case.

@strulovich, what do you think?

**Comment by strulovich** [comment]
I'm leaning towards changing this as suggested, at least for block functions for now.
I'll take on that.

**Comment by cgrushko** [comment]
This should now be fixed.
