### ISSUE TITLE
Build fails with Java 11 JDK

### ISSUE THREAD

**Issue by sgrimm** [facebookincubator/ktfmt#11]
This seems to be a problem in google-java-format rather than in ktfmt, so the actual issue here is just that it should be documented in the README. Running `mvn install` with a Java 11 JDK (AdoptOpenJDK 11.0.5+10) fails:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.0.0:jar (attach-javadocs) on project google-java-format: Execution attach-javadocs of goal org.apache.maven.plugins:maven-javadoc-plugin:3.0.0:jar failed.: NullPointerException -> [Help 1]
```

With a Java 8 JDK, it builds successfully.

**Comment by cgrushko** [comment]
Let's see if https://github.com/google/google-java-format/pull/429 helps.
