### ISSUE TITLE
One parameter per line if function prototype doesn't fit entirely in one line

### ISSUE THREAD

**Issue by Trigon** [facebookincubator/ktfmt#13]
```
private fun someMethod(
      metaData: JsonNode,
      interfaceIdex: Int,
      registryIdex: Int
  ): ArrayNode? {
```
For this one, it should be the right format, but after I use ktfmt, it changes to 
```
private fun getMethodsOrderedImplementationsWithMethods(
      metaData: JsonNode, interfaceIdex: Int, registryIdex: Int
  ): ArrayNode? {
```
Free feel to talk to me directly via workchat wyl@fb

**Comment by cgrushko** [comment]
1. Are you missing 2 spaces before `private fun…`?

I'd expect the output to be:
```
  private fun getMethodsOrderedImplementationsWithMethods(
      metaData: JsonNode, interfaceIdex: Int, registryIdex: Int
  ): ArrayNode? {
```

2. The parameters fit in one line, so ktfmt doesn't break them. Should it break? do you prefer the first version? are you aware of a style guide that mandates it? how should ktfmt decide whether to break the parameter list or not?

**Comment by Trigon** [comment]
@cgrushko 
Sorry, the 2 spaces are my issue, the output is the same as what you expect. 
After ktfmt makes the parameters be in the same line, the lint on phabricator complains about that. 
I think the style guide should be consistent between ktfmt and the lint in phabricator

**Comment by cgrushko** [comment]
ktfmt and detekct/ktlint disagree, so some friction between the linters is expected (we plan to disable detekt's formatting on files that ktfmt formats).

Again, we could change this formatting decision. I don't have a good sense of what's right to do.
cc @strulovich

**Comment by strulovich** [comment]
I think I agree with Carmi's expected style. We should disable some of Detekt's checks to match with this.

**Comment by sgrimm** [comment]
[Google's Kotlin style guide for Android](https://developer.android.com/kotlin/style-guide#functions) says arguments should be split across multiple lines if the function signature doesn't fit on one line. JetBrains' official Kotlin style guide is fuzzier; it says "closely related" arguments should be placed on the same line, but obviously ktfmt can't determine that.

**Comment by cgrushko** [comment]
My personal preference is to put all parameters in one line. Browsing Hack
code, which uses one parameter per line, is annoying to me because
parameters dominate the vertical space (ie, all I see while scrolling is
parameters).

Could be that it just needs getting used to, but we do expect lots of
interoperability with Java, so making it similar to java has its merits.

**Comment by Trigon** [comment]
I agree with being similar to java. Would the detekct changes the rule OR ktfmt replace detekct as the lint in diff tool?

**Comment by cgrushko** [comment]
Let’s move the detekt/ktfmt discussion internally.

**Comment by cgrushko** [comment]
I'll close this for now. We can revisit this if we run into examples where it's very clearly better to break before each parameter.
