### ISSUE TITLE
Import Optimization Feature

### ISSUE THREAD

**Issue by bchang7** [facebookincubator/ktfmt#17]
Can we support a similar mechanism from what ktlint has for import optimization?

**Comment by cgrushko** [comment]
Thanks for the request. Do you mean ktfmt should remove unused imports, similarly to google-java-format?

**Comment by bchang7** [comment]
yes - ktfmt should remove unused imports as well as sort alphabetically.

**Comment by hick209** [comment]
Sorting alphabetically was implemented on 3a7a096146773ac8656a8ecc8dd14e4037246c64.

Now we are just missing the import removal. Should we open a separated issue for that or just keep this one open?

**Comment by cgrushko** [comment]
Yes, let's reopen (or rename this issue) so it's clear.

I took a look at removing dead imports, but it wasn't immediately clear how to do it.

**Comment by strulovich** [comment]
Won't this be easy to solve by just remembering all name-references we see in a file, and removing all imports which have never been seen?

This might not remove 100%, but it should be correct to remove according to it.

**Comment by cgrushko** [comment]
Sounds good, let's try this. I think this approach is easy enough for first-time contributors?

**Comment by crsov** [comment]
Is it possible to disable this feature?

**Comment by strulovich** [comment]
It's possible only with the code right now:
https://github.com/facebook/ktfmt/blob/b25b5a00e07f8354fb8da047de5715bf42c9e40d/core/src/main/java/com/facebook/ktfmt/format/FormattingOptions.kt#L50

That's clearly not optimal, so I sent a commit to review to support it, once it is committed it will be merged to the open source version and the next version will support a flag to disable it.

**Comment by davidtorosyan** [comment]
Flag was added in ba8138dd887245dbff23c2d3b6643e3a0ba97d2c
