### ISSUE TITLE
Add support for IJ 2021.1 EAP

### ISSUE THREAD

**Issue by sureshg** [facebookincubator/ktfmt#173]
Plugin is not working after upgrading to the latest EAP

```
IntelliJ IDEA 2021.1 EAP (Ultimate Edition)
Build #IU-211.4961.30, built on January 26, 2021
Runtime version: 11.0.9.1+11-b1257.1 x86_64
macOS 10.15.7
```

**Comment by ColtonIdle** [comment]
@sureshg I had two issues when trying to get the plugin to work but I'm using 2021.1.1 and the plugin does in fact work.

I opened up #228 and #229 but I think we can close this issue since it does in fact support 2021.1+

**Comment by sureshg** [comment]
Yes, closing this as the plugin is working fine on 2021.1+
