### ISSUE TITLE
Avoid wildcard

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [facebookincubator/ktfmt#175]
I am trying with Spotless, should it take the config from `.editorconfig`?

**Comment by cgrushko** [comment]
I don't think so, but @franvis might know better.
Though - ktfmt is not a compiler and lacks information required to replace .* with individual imports, if that was your meaning.

**Comment by JavierSegoviaCordoba** [comment]
So this should be achieved via Spotless and another plugin.

@cortinico, your plugin supports this or has the same problem?

**Comment by cortinico** [comment]
> @cortinico, your plugin supports this or has the same problem?

I'm unsure what you're meaning exactly. But I don't think the Gradle plugin is of any help here as it's a wrapper on top of ktfmt
