### ISSUE TITLE
ktfmt-parent 0.20 is missing on Maven Central

### ISSUE THREAD

**Issue by cortinico** [facebookincubator/ktfmt#176]
I've been trying to bump the version of ktfmt used by ktfmt-gradle to 0.20 here: https://github.com/cortinico/ktfmt-gradle/pull/8

Seems like the `ktfmt` is declaring a dependency on a parent POM from `ktfmt-parent` (why?).

Looks like version `0.20` of `ktfmt-parent` is missing on Maven Central:
https://search.maven.org/artifact/com.facebook/ktfmt-parent

([Like to the broken CI run here](https://github.com/cortinico/ktfmt-gradle/pull/8/checks?check_run_id=1946937122))

**Comment by cgrushko** [comment]
Ugh... I ran `mvn` from the wrong directory, of course, so only `ktfmt` was uploaded.
Now, rerunning `mvn` from the correct directory fails because `ktfmt` cannot be updated. 
Looking into this, worst case I'll publish 0.21.

**Comment by cgrushko** [comment]
Ok, I managed to trick `mvn` into uploading only `ktfmt-parent`.
It's now over at https://repo1.maven.org/maven2/com/facebook/ktfmt-parent/0.20/ .

It might take another few hours to sync to other repositories.

**Comment by cgrushko** [comment]
Thanks for reporting!!!
