### ISSUE TITLE
Wrong indentation in a lambda

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [facebookincubator/ktfmt#177]
Introduced in `0.20`

```
class SomeClass {
    fun aLongMethodWhereLambdaIsNotInTheSameLine(foo: String, bar: String, baz: String) =
        someLambda {
        someClass.someMethod(foo = foo, bar = bar, baz = baz)
    }
}
```

should be

```
class SomeClass {
    fun aLongMethodWhereLambdaIsNotInTheSameLine(foo: String, bar: String, baz: String) =
        someLambda {
            someClass.someMethod(foo = foo, bar = bar, baz = baz)
        }
}
```

**Comment by cgrushko** [comment]
Mmm, looks like it's a result of https://github.com/facebookincubator/ktfmt/commit/6c7dd8dd6aaf1daa7d6633efb78b924c2e534fe1

I assume you're using dropbox style? it's lacking the extra indent we added for google-style. See the example at the very bottom of the commit. I think the way forward is to get rid of dropbox style, since it's not really maintained, and switch to 4/4 google style (and call it kotlinlang-style, maybe).

**Comment by JavierSegoviaCordoba** [comment]
Yeah, I am using dropbox-style. But currently, there is no way to use it with any Gradle plugin no?

I reproduced it in a test:

```
    @Test
    fun `handle lambda when it breaks line after an equal in a function`() =
        assertFormatted(
            """
      |fun aLongMethodWhereLambdaDoesntFitInTheSameLine(foo: String, bar: String, baz: String) =
      |  someLambda {
      |    someClass.someMethod(foo = foo, bar = bar, baz = baz)
      |  }
      |""".trimMargin())
```

Result:

```
# Input: 
####################
fun aLongMethodWhereLambdaDoesntFitInTheSameLine(foo: String, bar: String, baz: String) =
  someLambda {
    someClass.someMethod(foo = foo, bar = bar, baz = baz)
  }


# Output: 
####################
fun aLongMethodWhereLambdaDoesntFitInTheSameLine(foo: String, bar: String, baz: String) =
    someLambda {
  someClass.someMethod(foo = foo, bar = bar, baz = baz)
}
```

Even with Google Style, there is an error I think.

**Comment by JavierSegoviaCordoba** [comment]
I am checking the commit:

```
  @Test
  fun `assignment of a scoping function`() =
      assertFormatted(
          """
      |----------------------------
      |fun longName() =
      |    coroutineScope {
      |  foo()
      |  //
      |}
      |""".trimMargin(),
          formattingOptions = GOOGLE_FORMAT,
          deduceMaxWidth = true)
```

This is strange because the lambda content is not indented based on the lambda, it is indented based on the function
```
fun longName() =
    coroutineScope {
  foo()
  //
}
```

shouldn't be this?
```
fun longName() =
    coroutineScope {
        foo()
        //
    }

**Comment by JavierSegoviaCordoba** [comment]
IMO moving to kotlinlang-style is perfect, indeed I created a [post in discussions](https://github.com/facebookincubator/ktfmt/discussions/172).

I am currently introducing ktfmt in the company I works, should be great if you could expose this style this week so I can test it in the PR I am already creating. Do you think it is possible or it is very soon?

**Comment by cgrushko** [comment]
@JavierSegoviaCordoba we'll try :) in the meanwhile, don't wait for us - clone the repo and build at head and see if it's of use for you at all.

**Comment by JavierSegoviaCordoba** [comment]
I am trying this again with the latest IDEA and the 4 styles version:

## default
Current:
![image](https://user-images.githubusercontent.com/7463564/110122521-053cde00-7dc0-11eb-8c9b-7d6f71765c76.png)

Should be:
![image](https://user-images.githubusercontent.com/7463564/110122819-64025780-7dc0-11eb-84f7-87731028902d.png)


## dropbox
Current:
![image](https://user-images.githubusercontent.com/7463564/110122571-138afa00-7dc0-11eb-8431-c689e59f3eb0.png)

Should be
![image](https://user-images.githubusercontent.com/7463564/110122872-7ed4cc00-7dc0-11eb-9665-72253fb8dd18.png)


## google
Current:
![image](https://user-images.githubusercontent.com/7463564/110122608-1f76bc00-7dc0-11eb-997e-dfe9dadfdbce.png)

Should be (I am not sure if println should have 2 or 4 spaces):
![image](https://user-images.githubusercontent.com/7463564/110123014-ad52a700-7dc0-11eb-9965-78474a62c19c.png)


- kotlinlang

Current:
![image](https://user-images.githubusercontent.com/7463564/110122649-2a315100-7dc0-11eb-9cd4-5d92433919cd.png)

Should be:
![image](https://user-images.githubusercontent.com/7463564/110123125-cd826600-7dc0-11eb-9809-30d1686d8409.png)

I am not sure about the 8 space indent, I think it should be 4 like Dropbox does.

**Comment by cgrushko** [comment]
This weirdness is a limitation of the underlying engine: https://github.com/google/google-java-format/issues/556.
I agree that your alternative forms are better, but I'm not sure how get it right now.

**Comment by JavierSegoviaCordoba** [comment]
But it is the same use case that google/google-java-format#556? In my case, it is jumping to the next line because it doesn't fit in one line, and that is fine, the problem is the random indentation in the curly braces.

And some time ago I think that was not happening 🤔 

If it is caused by this https://github.com/facebookincubator/ktfmt/commit/6c7dd8dd6aaf1daa7d6633efb78b924c2e534fe1 cannot be improved/reverted?

**Comment by cgrushko** [comment]
Indeed, https://github.com/facebookincubator/ktfmt/commit/6c7dd8dd6aaf1daa7d6633efb78b924c2e534fe1 is the root cause. 
Improving it is something I'd like to do, but haven't found a straightforward way to do so right now.
As for reverting - I think the benefits outweigh the cost. Do you disagree? do you run into this problem a lot?

**Comment by JavierSegoviaCordoba** [comment]
I agree and I can live with it trying to changing some large names to avoid this problem, don't worry :)

**Comment by bethcutler** [comment]
Chiming in to say this issue has been reported internally within Google as well.  Would be nice to find a fix, though I can respect the fact that it's complicated!

**Comment by JavierSegoviaCordoba** [comment]
@bethcutler do you know if it is fixed there? I have checked that this issue happens a lot when you are using ktor client

**Comment by JavierSegoviaCordoba** [comment]
Not a good new... https://github.com/google/google-java-format/issues/19#issuecomment-903958306, not sure if it is the same.

**Comment by ColtonIdle** [comment]
I wonder if this is also the cause of this issue with compose code which relies heavily on trailing lambdas: https://github.com/facebookincubator/ktfmt/issues/249

**Comment by nreid260** [comment]
On the Google side, we're considering that it might be better to revert. We'd prefer a formatting that is consistently adequate vs one that is usually really good but fails a few percent of the time.

I did some digging into how to fix this bug, and while it's possible, it's pretty hacky. The underlying problem is that google_java_format strongly adheres to the rectangle rule, which https://github.com/facebookincubator/ktfmt/commit/6c7dd8dd6aaf1daa7d6633efb78b924c2e534fe1 violates. In order to express https://github.com/facebookincubator/ktfmt/commit/6c7dd8dd6aaf1daa7d6633efb78b924c2e534fe1 formatting correctly, we need to futz around with conditional indents across many syntactic levels.

This issue is common to all "block-like expression", which Kotlin has several of (e.g. `if`, `when`). If we could add support for such constructs directly into google_java_format, it might make sense, but it currently isn't obvious how to do that. Until then, consistency across all block-like expressions is also desirable.

**Comment by cgrushko** [comment]
For tracking, this is how it looks like in 0.31 using kotlinlang style:
```
class SomeClass {
    fun aLongMethodWhereLambdaIsNotInTheSameLine(foo: String, bar: String, baz: String) =
            someLambda {
        someClass.someMethod(foo = foo, bar = bar, baz = baz)
    }
}
```

cc @strulovich

**Comment by JavierSegoviaCordoba** [comment]
What do you think about reverting @cgrushko. Personally don't see a lot of them

```
// preferable but I don't see this a lot in the code
fun foo() = {
  doItOnce()
  doItTwice()
}

// I like this because it is very Kotlin like
fun foo() = someLambda {
  doItOnce()
  doItTwice()
}

// I can live with this instead of having the issue
// because I see more of the issue than this use case
fun foo() =
  {
    doItOnce()
    doItTwice()
  }
  
// I have no issues with this and has consistence with other block formats
// even it not being very Kotlin like.
fun foo() =
  someLambda {
    doItOnce()
    doItTwice()
  }
```

**Comment by nreid260** [comment]
I've sent https://github.com/facebookincubator/ktfmt/pull/280 to fix this issue, at least for the majority of cases.

I'm still not sure the special case is worth it overall, but the fix isn't notably more complex than the current implementation. It might be easier to debate philosophy when there's no clear bug.

**Comment by JavierSegoviaCordoba** [comment]
I think this is already fixed, @cgrushko feels free to reopen if not.
