### ISSUE TITLE
Publish artifacts to Maven Central or JCenter

### ISSUE THREAD

**Issue by sgrimm** [facebookincubator/ktfmt#18]
It'd be nice to have official jars available in one of the usual places for jar distribution, rather than having to build the code locally. Among other things, being able to specify ktfmt as a dependency would make it easier to build, say, a Gradle or Maven plugin to run it as part of a build process.

**Comment by cgrushko** [comment]
We've been extensively dogfooding ktfmt and are almost happy with the results; I think we're very close to version 1.0, at which point I'll tag it, create a release and publish artifacts. 
If I see it takes longer than a few days, I'll publish 0.1 binaries.

**Comment by cgrushko** [comment]
@sgrimm I published v0.11 to Maven Central - https://search.maven.org/artifact/com.facebook/ktfmt/0.11/jar

This version has some rough edges around raw strings - see release notes at https://github.com/facebookincubator/ktfmt/releases/tag/v0.11

I'll leave this Issue open until we release v1.0.

**Comment by cgrushko** [comment]
I think this is now streamlined enough to close this Issue.
