### ISSUE TITLE
Return type moved to its own line if signature too long

### ISSUE THREAD

**Issue by sgrimm** [facebookincubator/ktfmt#19]
The [Kotlin style guide](https://kotlinlang.org/docs/reference/coding-conventions.html#formatting) says function signatures that don't fit on one line should be formatted like

```
fun longMethodName(
    argument: ArgumentType = defaultValue,
    argument2: AnotherArgumentType
): ReturnType {
  // body
}
```

But in cases where the argument list fits on one line but the return type pushes it over the limit, ktfmt renders this as

```
fun longMethodName(argument: ArgumentType = defaultValue, argument2: AnotherArgumentType):
    ReturnType {
  // body
}
```

**Comment by cgrushko** [comment]
Closed via https://github.com/facebookincubator/ktfmt/commit/f259dd66f79a551f0cf725462a85023774cc7f2c.
