### ISSUE TITLE
Space inserted after link in KDoc, even when not indended.

### ISSUE THREAD

**Issue by bethcutler** [facebookincubator/ktfmt#190]
In KDoc, if you want to refer to the plural of an object that has a singular name, you might write:
```kotlin
/** There are many [FooObject]s. */
```

ktfmt inserts a space after the link, which is unexpected:
```kotlin
/** There are many [FooObject] s. */
```

**Comment by bethcutler** [comment]
Related, and more problematic issue:
If there is a parenthetical comment immediately following an inline object link, the space between them will be removed, unintentionally turning the link and parenthetical into a non-functional Markdown link.

```kotlin
/** BEFORE Please see [onNext] (which has more details) */

/** AFTER Please see [onNext](which has more details) */
```

**Comment by cgrushko** [comment]
We didn't realize these are all valid KDocs. 
In the meantime, a workaround for the second example is to use a letter or digit after the [link]. I know, not really a solution :) 

I'll try to tackle this tomorrow. The hard part is to decide what behavior we should have. I'm leaning towards collapsing multiple  spaces into a single space and not add any spaces anywhere.

**Comment by cgrushko** [comment]
Looks like the issue is that the kdoc lexer we use (bundled with the compiler) is lacking and would report confusing data to ktfmt. 

I want to look into using Dokka instead.

**Comment by SanjayVas** [comment]
Here's another example that breaks the KDoc.
```
/** The final produced value may have [size][ByteString.size] < [bufferSize]. **/
```
becomes
```
/** The final produced value may have [size] [ByteString.size]< [bufferSize]. **/
```

This not only breaks the KDoc reference, but also incorrect removes the space after it.
