### ISSUE TITLE
ktfmt fails to parse multiple statements separated with semicolons

### ISSUE THREAD

**Issue by cortinico** [facebookincubator/ktfmt#194]
Original report from Slack: https://kotlinlang.slack.com/archives/C0BJ0GTE2/p1615839796241500?thread_ts=1615809255.232100&cid=C0BJ0GTE2

The following code causes ktfmt to crash:

```kotlin
val res = when {
    true -> "1"; false -> "0"
    else -> "-1"
}
```

Specifically the tool fails with: `error: did not generate token ";"`
A full stacktrace is here: https://pastebin.com/Jk3hHk50

**Comment by cgrushko** [comment]
Should we preserve the semicolon? should we drop it and move the `false` branch to the next line?
