### ISSUE TITLE
Space after KDoc link is removed

### ISSUE THREAD

**Issue by sgrimm** [facebookincubator/ktfmt#20]
Maybe already covered by #15 but ktfmt changes

```
/**
 * Doc line with a reference to [AnotherClass] in the middle of a sentence
 */
```

to

```
/**
 * Doc line with a reference to [AnotherClass]in the middle of a sentence
 */
```

**Comment by cgrushko** [comment]
This is fixed via https://github.com/facebookincubator/ktfmt/commit/0ef289ed278a25336ccfafa0c038ed9a9892db3a and a bunch of other KDoc diffs.
