### ISSUE TITLE
Android Studio "ktfmt Settings" missing from Preferences

### ISSUE THREAD

**Issue by brianliyang** [facebookincubator/ktfmt#200]
I'm trying to enable ktfmt for my project but I noticed that the setting is missing from my Preference pane. I'm using Android Studio 4.1.1 (on macOS) and installed the plugin directly from the Marketplace. I've restarted my IDE and I can't seem to find the "ktfmt Settings" option as described by the installation instructions. The instructions say it should be under the "Editor" group.

I've tried this on two separate computers and neither installations of Android Studio show this option after installing the plugin from Marketplace. Am I missing some configuration or setting?

<img width="1249" alt="Screen Shot 2021-03-27 at 11 51 53 AM" src="https://user-images.githubusercontent.com/5104934/112731263-66555e80-8ef3-11eb-8a82-3fd59c7d2c38.png">

**Comment by cgrushko** [comment]
I think it might have to do with ktfmt's requirement of JDK 11 and up, while AS uses JDK 8 (if I remember correctly). 

IIRC, there's a way to run AS with a different runtime. 

Can you paste your About screen? It should show the JDK version. 

@tyvsmith and I discussed a way to make ktfmt work with JDK 8.

**Comment by brianliyang** [comment]
Gotcha, yeah here's my About screen. If that's the case, I'll have to see if I can change the runtime.

<img width="639" alt="Screen Shot 2021-03-27 at 12 43 01 PM" src="https://user-images.githubusercontent.com/5104934/112732907-0a420880-8efa-11eb-93b1-d90f1e3aa35a.png">

**Comment by brianliyang** [comment]
Installing the "Choose Runtime" plugin from Marketplace and changing my runtime to JDK 11 did make the option appear, guess that was it!

**Comment by brianliyang** [comment]
I should note that there are some stability issues with running JDK 11 with Android Studio. Specifically I'm getting an instant crash when opening XML layout files in Android Studio. I haven't found a JDK 11 runtime package that doesn't cause this issue so it's a little annoying right now. If anyone has a workaround or knows a stable runtime package to download from the "Choose Runtime" plugin, please feel free to share that.

A cursory search of "Android Studio java 11" on Google doesn't seem to pull up very many results. I assume it's not robust yet.

**Comment by cgrushko** [comment]
Progress on JDK 8 support: https://github.com/facebookincubator/ktfmt/issues/201
