### ISSUE TITLE
Feature Request: Disable formatting on specific files (or sections of files)

### ISSUE THREAD

**Issue by bethcutler** [facebookincubator/ktfmt#209]
Would it be possible (or is it already possible) to include comments in a file that would disable formatting between them?
e.g.

```kotlin
  // disable ktfmt
  // ...code that should not be formatted
  // enable ktfmt
```

My use case for this is I have kotlin files that contain instructions in comments with a specific formatting
```kotlin
  //- The dash in this comment must immediately follow the //
```

ktfmt adds a space before the -, which effectively disables the instruction.

**Comment by cgrushko** [comment]
Drawing on https://github.com/google/google-java-format/wiki/FAQ#why-cant-i-use-magic-comments-to-disable-formatting-for-certain-sections-of-code, this is something we'd like to avoid. 

Ideally, using triple-backtick should help here. If it's not working properly, let's work on this in a separate issue. I'll close the issue for now.
