### ISSUE TITLE
Break before Elvis operator rather than after

### ISSUE THREAD

**Issue by sgrimm** [facebookincubator/ktfmt#21]
Both the official and Android Kotlin style guides are silent on this topic, but I think breaking before the Elvis (`?:`) operator if the expression doesn't fit on one line, rather than after it, would improve readability.

Example:

```kotlin
someObject.someMethodReturningCollection()
    .map { it.someProperty }
    .find { it.contains(someSearchValue) }
    ?: someDefaultValue
```

Currently ktfmt would render this as

```kotlin
someObject.someMethodReturningCollection()
    .map { it.someProperty }
    .find { it.contains(someSearchValue) } ?:
    someDefaultValue
```

This is of course totally syntactically correct but I think it makes the flow of control a little harder to follow, and is inconsistent with the formatting of `?.` which ktfmt puts at the start of the line.

**Comment by cgrushko** [comment]
Thanks! Looks better, I agree.
One concern - could this confuse the compiler or change semantics in any way?

**Comment by strulovich** [comment]
I agree. We tried to see if this can cause some ambiguity of expressions, but it seems safe for now.

**Comment by sgrimm** [comment]
For what it's worth (though it doesn't quite answer the question), this is how IntelliJ does it by default.

**Comment by cgrushko** [comment]
That's as good answer as we could've hoped for :)

**Comment by cgrushko** [comment]
Fixed.
