### ISSUE TITLE
Space after link at end of sentence in KDoc

### ISSUE THREAD

**Issue by sgrimm** [facebookincubator/ktfmt#22]
The handling of links in the middle of sentences is much better now, but the new behavior introduced one quirk.

```
/**
 * This is a comment that links to [AnotherClass].
 */
```

gets formatted as

```
/**
 * This is a comment that links to [AnotherClass] .
 */
```

**Comment by cgrushko** [comment]
cc @strulovich

**Comment by strulovich** [comment]
This was fixed in https://github.com/facebookincubator/ktfmt/commit/c57cb64056325a76882a17fb489d7ae48ee72368#diff-1930e9b21d36d1f420b9a81b660b4b44

**Comment by hick209** [comment]
We should close this issue, @cgrushko
