### ISSUE TITLE
The ktfmt plugin for IntelliJ IDEs isn't overriding cmd+opt+L

### ISSUE THREAD

**Issue by ColtonIdle** [facebookincubator/ktfmt#223]
I've been trying out ktfmt today and I really like it, but the big selling point to me is the intellij plugin. If I enable the plugin and then press cmd + shift + l, the results are identical to the results without it. And the real kicker is that if I run the jar directly against my project the formatting is different. I'm convinced cmd + opt + L isn't actually overriding the Android Studio shortcut.

Is there any way to tell if the reformat was applied by ktfmt?

I'm using AS Canary 14

**Comment by cgrushko** [comment]
First thing to check - is the plug-in enabled? Go to settings and search for ktfmt, then check the Enabled checkbox. 
If there's no such Settings, it's probably due to AS running on JDK 8 while ktfmt requiring JDK 11.

**Comment by ColtonIdle** [comment]
<img width="1094" alt="Screen Shot 2021-05-02 at 8 57 07 AM" src="https://user-images.githubusercontent.com/31751141/116813950-767ce100-ab24-11eb-8a47-9c9e6c559518.png">

It's enabled. Is there any way to tell if cmd opt L is actually applied from the plugin rather than me just guessing?

**Comment by cgrushko** [comment]
This looks correct. IntelliJ has some logs (shows up in the right bottom corner), but I'm not an expert in plugins and how to debug them.

**Comment by ColtonIdle** [comment]
@cgrushko thanks for the response. I don't see any logs regarding ktfmt so I guess I will keep this open to see if anyone else that maintains the plugin can chime in.

**Comment by cgrushko** [comment]
@ColtonIdle  that looks like ktfmt failed to parse the file, or alternatively that it failed an internal assertion.
Can you try pasting the file onto https://facebookincubator.github.io/ktfmt/ , formatting, and seeing if it reports an error?

**Comment by ColtonIdle** [comment]
ktfmt website does not fail seems to be due to another issue.

Closing in favor of #228
