### ISSUE TITLE
Cmd line jar formatter isn't formatting my .kts build files

### ISSUE THREAD

**Issue by ColtonIdle** [facebookincubator/ktfmt#224]
I've been trying out ktfmt today and I found that the cmd line jar formatter isn't formatting my .kts build files.

I'm using:

`java -jar /path/to/ktfmt-<VERSION>-jar-with-dependencies.jar .`

and it fixed all .kt but not .kts files.

Interesting enough I tried using the spotless plugin with ktfmt and that indeed formatted my .kts files so I'm not sure what the difference is between the two since I thought spotless just delegates to the jar. Thanks!

**Comment by cgrushko** [comment]
Glad you liked it!
The culprit is Main.kt line 124, which only considers files with a "kt" extension. 
Would you be interested in sending a PR? (If you do, please also update the corresponding test, if there is one)

**Comment by ColtonIdle** [comment]
Hm. I wonder if it's purposefully missing, but I will put it on my todo list to update the test and add .kt.

Thanks
