### ISSUE TITLE
Support for Kotlin 1.5 value classes

### ISSUE THREAD

**Issue by LeonRa** [facebookincubator/ktfmt#236]
The recently released Kotlin 1.5 introduces [inline (or value) classes](https://kotlinlang.org/docs/whatsnew15.html#inline-classes) which offer a nice way to enforce type safety without memory overhead. The formatter is currently not recognizing `value class`, resulting in line breaks.

For the example given in the link above:

**Input:**

```
@JvmInline 
value class Password(val s: String)
```

**Expected:**

```
@JvmInline value class Password(val s: String)
```

**Actual:**

```
@JvmInline value 

class Password(val s: String)
```

**Comment by cgrushko** [comment]
What version are you using?
I'm trying to repro using https://facebookincubator.github.io/ktfmt/ (which is running 0.25) and it gives me a reasonable

```
@JvmInlineBla
value class PasswordBlaBlaBla(val s: String)
```

(I added some words to make it overflow the 50 column limit, which is the minimum in the online formatter)

**Comment by LeonRa** [comment]
Ah, it may appear that we need to update. We are currently using 0.22 so I will give 0.25 a try and will post back. Sorry about that, definitely should have checked against the latest first

**Comment by cgrushko** [comment]
I'm surprised 0.22 worked at all, since it was using the Kotlin 1.4 compiler. Maybe the keyword was there but was treated differently? weird, but happy it works :)

**Comment by LeonRa** [comment]
Confirming that 0.25 gives the expected output. Thanks again!
