### ISSUE TITLE
Reconsider 2 vs 4 space indentation

### ISSUE THREAD

**Issue by eyalgu** [facebookincubator/ktfmt#24]
ktfmt looks like a very promising alternative to ktlint!
However, the 2 space format makes it pretty much impossible for me to introduce ktfmt on any reasonably sized existing codebase. Given that consistent indentation is so important (especially within the same file) I don't think I can even try out ktfmt with the 2 spaces choice (I could live with lots of other migration inconsistencies, but this one would be to glaring),

4 spaces are the absolute standard in any existing Kotlin codebase, so I believe that this decision will really hinder people's ability to use this library. 
I would suggest you reconsider this decision in order to unlock wider adoption :)

**Comment by eyalgu** [comment]
For reference, the Kotlin formatting guideline, which is why everyone does 4 (including all other popular formatters) https://kotlinlang.org/docs/reference/coding-conventions.html#formatting

**Comment by eyalgu** [comment]
Actually, indent size seems to be one of the only configurable values in ktlint (probably because it's so important to have that consistent). I know (and love) your attitude against configuration, but this could be good candidate for an exception 


For completeness, the other 2 config values ktlint calls out are:
1) max line length
2) insert new line at end of file

I feel way less strongly about these 2, though I would also appreciate a way to bump the line length like in ktlint.

**Comment by cgrushko** [comment]
@eyalgu, give it a try - `ktfmt --dropbox-style Filename.kt`
