### ISSUE TITLE
Crash with synchronized - new in 0.26

### ISSUE THREAD

**Issue by bethcutler** [facebookincubator/ktfmt#243]
This sample code:
```kotlin
class Foo {
  companion object {
    var instance: Foo? = null

    fun getInstance() {
      return instance ?: synchronized(Foo::class) {
        Foo().also { instance = it }
      }
    }
  }
}
```

crashes the formatter with
```
error: did not generate token "("
com.google.googlejavaformat.FormattingError: 9:51: error: did not generate token "("

        at com.google.googlejavaformat.OpsBuilder.sync(OpsBuilder.java:231)
        at com.facebook.ktfmt.KotlinInputAstVisitorBase.sync(KotlinInputAstVisitorBase.kt:2298)
        at com.facebook.ktfmt.KotlinInputAstVisitorBase.visitLambdaExpression(KotlinInputAstVisitorBase.kt:806)
 ...
```

The formatter handled this fine in 0.25.

**Comment by msfjarvis** [comment]
This is not limited to synchronized, and happens for me with any statement that looks like this:

```
variable = method(arbitraryValue) { // Trailing lambda
}
```

In my codebase it fails [on this line](https://github.com/android-password-store/Android-Password-Store/blob/29041cf5611dfb8c15a68581167fe3b09753d1f8/app/src/main/java/dev/msfjarvis/aps/ui/settings/RepositorySettings.kt#L129).

**Comment by cgrushko** [comment]
:(
Could this be related to https://github.com/facebookincubator/ktfmt/commit/57a2a812cc046bf39e8848ee1bdadd19b9015565 ? cc @steventrouble

**Comment by steventrouble** [comment]
Investigating, thanks for the ping!

**Comment by steventrouble** [comment]
Successfully reproduced with a unit test, now looking into where the bug is.

**Comment by steventrouble** [comment]
Think I found the cause. `processLambdaOrScopingFunction` was not made to handle call expressions with arguments or type arguments. I think we should reuse the logic from `visitCallElement` here instead of having custom logic, but I'm not sure what the consequences of that would be.
E.g: Convert this:

```
val call = initializer as KtCallExpression
call.calleeExpression?.accept(this)
builder.space()
call.lambdaArguments.forEach { it.getArgumentExpression()?.accept(this) }
```

to this

```
with(call) {
  visitCallElement(
      calleeExpression,
      typeArgumentList,
      valueArgumentList,
      listOf(), // No lambda, see below
      lambdaIndent = ZERO)
}

// Pass the lambda separately to keep it at a lower syntax level
builder.space()
call.lambdaArguments.forEach { it.getArgumentExpression()?.accept(this) }
```

WDYT, is this a safe change to make?

**Comment by steventrouble** [comment]
Example pull request here that I think *should* fix the issue, but I won't be able to test it for regressions on real code until tomorrow or possibly later this week: https://github.com/facebookincubator/ktfmt/pull/244

**Comment by cgrushko** [comment]
@steventrouble I'll see if a rollback fixes this crash, and if it does I'll commit it and release a fixed version without it, so we have more time to fix forward.

**Comment by steventrouble** [comment]
SG, thanks Carmi!
