### ISSUE TITLE
Unicode characters through stdin not handled properly with non-standard UTF setting

### ISSUE THREAD

**Issue by bethcutler** [facebookincubator/ktfmt#250]
Passing unicode characters on stdin with standard encoding, ktfmt works as expected:
```
echo "// 日本語" | java -jar <ktfmt-jar> -
// 日本語
```

With a non-standard encoding, however, the characters are converted to ??:
```
echo "// 日本語" | LC_CTYPE=en_GB.UTF-8 java -jar<ktfmt-jar> -
// ?????????
```

**Comment by cgrushko** [comment]
@bethcutler , we're having trouble reproducing this. What OS and terminal are you using?
We tried Macbook + zsh and CentOS + bash; building using {Java 8, Java 12} and running on {Java 8, Java 12}.
Please reopen if it's still happening :)
