### ISSUE TITLE
Inconsistent indentation of "when" branches

### ISSUE THREAD

**Issue by sgrimm** [facebookincubator/ktfmt#26]
It's possible to get three different indent levels in a single `when` statement. Ktfmt output:

```kotlin
fun test(x: String) {
  when (x) {
    "foo" ->
        synchronized(this) {
          println("A statement")
          println("Another statement")
        }
    "bar" ->
    // A comment
    println("Okay")
    "baz" -> {
      println("Just a statement")
      println("And another")
    }
  }
}
```

**Comment by cgrushko** [comment]
heh :) well, the first and third are "expected", right? the first one is a continuation indent, whereas the third one is a block indent.

The second is clearly a bug. Should be, at the minimum, a continuation indent.

What do you think?

**Comment by cgrushko** [comment]
I'm going to close the issue since the 2nd case is now fixed. The others are problematic to change without introducing inconsistencies into the formatter. Let me know what you think.

**Comment by sgrimm** [comment]
Yeah, that's better now. I would personally prefer block indent for single-statement `when` branches so the indentation doesn't change if you add braces and is consistent when you have a mix of block and single-statement branches, but I am completely on board with the idea that ktfmt should be opinionated even if I don't agree with 100% of its opinions. I agree that only the second case was clearly a bug. Thanks!

**Comment by sgrimm** [comment]
I guess a stronger argument is that the Kotlin style guide uses block indent for the single-statement `when` branch case. https://kotlinlang.org/docs/reference/coding-conventions.html#formatting-control-flow-statements

**Comment by cgrushko** [comment]
The Kotlin style guide uses indentation of continuation == block == 4, whereas ktfmt uses 4 and 2 respectively; so, the Kotlin style guide gets away with it because there's no difference. (unless I was looking at the wrong place?)

**Comment by sgrimm** [comment]
Yeah, that's fair; the lack of distinction between continuation and block indent makes their intent ambiguous. My preference is for block indent but like I said, I totally acknowledge I'm bikeshedding at the moment and am happy with the fix for the second case.
