### ISSUE TITLE
Don't force CRLF

### ISSUE THREAD

**Issue by mpetuska** [facebookincubator/ktfmt#260]
Currently looks like ktfmt is forcing CRLF line endings when validating formatting. This is far from desirable as it [breaks](https://github.com/mpetuska/klip/runs/4288478452?check_suite_focus=true#step:9:476) MPP builds on windows hosts for generated sources. I think it would be best to force consistent line endings and instead maybe expose some config property/flag to enable it.

**Comment by cgrushko** [comment]
Are you sure? There's explicit code that detects the existing new line sequence and uses it when outputting. Can you upload a sample file? Or even better, submit a unit test?

**Comment by mpetuska** [comment]
Have a look at linked build and gradle build scan. The error basically says to replace all `\n` with `\r\n`. Note that this only affects generated code. On that note, it'd be great if we could somehow exclude generated code from ktfmt scope.

**Comment by cgrushko** [comment]
It sounds like the generated file has \n, which kftmf preserves?
If that's the case, that's working as intended.

One option is to convert the generated file to \r\n, the other is to exclude it from formatting. This project (https://github.com/facebookincubator/ktfmt/) doesn't provide a Gradle plugin, so I suggest filing a feature request for skipping files in the Gradle plugin's project repo (if there isn't a way to do so already).

Please reopen if I got anything wrong.
