### ISSUE TITLE
Failure on bodiless enum class

### ISSUE THREAD

**Issue by nreid260** [facebookincubator/ktfmt#265]
The following code builds under kotlinc v1.6.10 but fails in ktfmt:

```kt
package ktlint.examples

enum class EnumNoBody()

```

ktfmt reports:

```
22: error: expected token: ''; generated { instead
```

**Comment by hick209** [comment]
@mpetrov is working on this issue on https://github.com/facebookincubator/ktfmt/pull/263, which I hope to land today
