### ISSUE TITLE
When formatting from stdin, ktfmt prints nothing to stdout if there are no changes

### ISSUE THREAD

**Issue by elizagamedev** [facebookincubator/ktfmt#267]
This behavior seems like it was intended for humans, but unfortunately some auto-code formatting packages for text editors do not handle this case well at all, for example, [apheleia](https://github.com/raxod502/apheleia)). I don't remember this being an issue until the past few months, so I assume this change happened somewhere in one of the later 0.2X releases.

A simple option like `--always-print` or something similar would fix the issue.

**Comment by raxod502** [comment]
I'm the author of the aforementioned code formatting package. For reference, the downstream issue is at https://github.com/raxod502/apheleia/issues/66. I would like to add my voice to this issue. Quoting my comment at the other issue:

> Maybe there's something I'm missing, but this behavior seems like obviously a bug and I can't think of any possible use case where it would be desired. I don't know how you would actually use the formatter in any other tooling. Format the file, direct the output to the formatted file... then manually check if the formatted file is empty, and if it is, copy the original? That seems bizarre.

So I would advocate not for adding an option, but simply changing the behavior unconditionally. This is how all other code formatters behave that I am currently aware of.

**Comment by cgrushko** [comment]
So sorry, totally missed this Issue. I'm landing a fix now.

**Comment by cgrushko** [comment]
Fixed by https://github.com/facebookincubator/ktfmt/commit/f85414c97698f0ae7aac392a31020fb558b96a6a
