### ISSUE TITLE
Formatting long extension function declarations results in lines that are too long, and should be split across multiple lines instead.

### ISSUE THREAD

**Issue by EanLombardo** [facebookincubator/ktfmt#268]
Formatting a line like
```
suspend fun AbstractFactoryModuleFactoryBuilderFactoryModuleFactoryBuilder.constructBuilderModuleFactory()
```

Results in the same line, which exceeds 100 characters in width.

The kotlin android [style guide for line wrapping](https://developer.android.com/kotlin/style-guide#line_wrapping) indicates that the line should be split at the nearest "operator like" symbol, in this case the line should be formated to.

```
suspend fun AbstractFactoryModuleFactoryBuilderFactoryModuleFactoryBuilder
   .constructBuilderModuleFactory()
```

**Comment by strulovich** [comment]
Sorry for the delay, this will be fixed (for functions at least) with the next release.
