### ISSUE TITLE
Crash when trying to format a single-lambda argument invocation with a trailing comma

### ISSUE THREAD

**Issue by bethcutler** [facebookincubator/ktfmt#285]
```kotlin
foo({ it },)    // Bad
foo({ it })     // Ok
foo(0, { it },) // Ok
```

produces this error:
```
error: expected token: ','; generated ) instead
```

**Comment by strulovich** [comment]
Nice catch. I have a fix, but I'm not sure how would we like it formatted.

For now this will be `foo({ it },)` which is weird.

**Comment by JavierSegoviaCordoba** [comment]
I guess it should be

```kotlin
foo(
    { it },
)
```

But it looks strange having a lambda inside parenthesis without using named params, the linter even suggests changing it. But not sure if ktfmt should force formatting so

```kotlin
foo { it }
```

**Comment by cgrushko** [comment]
Fixed by https://github.com/facebookincubator/ktfmt/commit/5e0054a16011e4e24d0892d2583461f94a6fbbb8
