### ISSUE TITLE
Gradle dependency resolution issues with parent POM

### ISSUE THREAD

**Issue by RanadeepPolavarapu** [facebookincubator/ktfmt#30]
**build.gradle**: 
```gradle
  compile group: 'com.facebook', name: 'ktfmt', version: '0.12'
```

Leads to an error of: 
```
Could not resolve com.facebook:ktfmt:0.12.

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

It has to do with the parent pom not being available by name on the published repo (https://repo1.maven.org/maven2/com/facebook/ktfmt/0.12/).

Gradle is essentially traversing the pom tree and trying to resolve `ktfmt-parent` artifact:

`https://repo.jfrog.org/artifactory/libs-release-bintray/com/facebook/ktfmt-parent/0.12/ktfmt-parent-0.12.pom?referrer`

Maybe we can rename the parent pom artifact to simply `ktfmt` and then rename the child modules to `ktfmt-core` and `ktfmt-vendor`?

**Comment by RanadeepPolavarapu** [comment]
Just for additional context, I ran into this issue while adding a spotless plugin integrating `ktfmt` into spotless for ease of use.

The soon-to-be PR ready diff is available here: https://github.com/diffplug/spotless/compare/master...RanadeepPolavarapu:feat/ktfmt.

Ran into this issue when running the integration tests which has Gradle resolve `ktfmt` from Maven Central and that causes gradle to traverse POM tree and thus leading to this issue.

**Comment by cgrushko** [comment]
Exciting!!!
I'll try to look at it ASAP. Thanks for the report.

**Comment by cgrushko** [comment]
So, the 'parent' thing is due to us building `ktfmt` against a local checkout of `google-java-format`. It's done so we don't need to wait for GJF releases after we make changes to it that we need for ktfmt. 
I'll see if we still need it, and whether it's actually a problem (GJF might be ok with releasing for us)

cc @cushon

**Comment by cgrushko** [comment]
@RanadeepPolavarapu, can you give it another try? use the coordinates `com.facebook:ktfmt:0.13`.

**Comment by RanadeepPolavarapu** [comment]
@cgrushko Perfect, thanks for the update. I can confirm gradle resolution is working under version `0.13`.

Opened diffplug/spotless#569, hopefully should be available via Spotless soon. Will contribute the IntelliJ plugin once I finish the spotless one.

**Comment by cgrushko** [comment]
Nice!!! I'll release 0.13 then.
