### ISSUE TITLE
Artifacts for v0.36 not available on MavenCentral

### ISSUE THREAD

**Issue by msfjarvis** [facebookincubator/ktfmt#313]
I can't seem to find the published JARs for ktfmt over on [search.maven.org](https://search.maven.org/artifact/com.facebook/ktfmt) or [repo1.maven.org](https://repo1.maven.org/maven2/com/facebook/ktfmt/), is this intentional?

**Comment by cgrushko** [comment]
Mmm... no, the publishing job must've failed. I'll take a look later tonight or on Sunday. Sorry about that..

**Comment by msfjarvis** [comment]
Absolutely no rush on my end, just wanted to see if you folks were aware 😄

**Comment by cgrushko** [comment]
This is now resolved. Thanks for drawing our attention :)

**Comment by msfjarvis** [comment]
Thanks for the quick resolution!
