### ISSUE TITLE
Chain after Elvis operator changes indentation

### ISSUE THREAD

**Issue by att14** [facebookincubator/ktfmt#326]
For kotlinlang/Google style, an Elvis that is wrapped keeps the indentation of the Elvis, but if it is chained it adds another indent.

```
        val foobar =
            someMethod()
                ?: return SomeClass(
                    myCoolVariable,
                    message =
                        "Error doing something so this line is really long and makes the rest wrap"
                )
```

Adding a chain:

```
        val foobar =
            someMethod()
                ?: return SomeClass(
                        myCoolVariable,
                        message =
                            "Error doing something so this line is really long and makes the rest wrap"
                    )
                    .left()
```

I would expect this to be formatted as:

```
        val foobar =
            someMethod()
                ?: return SomeClass(
                    myCoolVariable,
                    message =
                        "Error doing something so this line is really long and makes the rest wrap"
                )
                    .left()
```

It looks like this might be because Java-like adds the indent to differentiate the parameters vs. the chain since they keep the parenthesis on the previous line.

**Comment by att14** [comment]
Actually, this happens with any multi-lined parameters with a following chain.

```
            val argsIndent =
                Indent.If.make(
                        nameTag,
                        expressionBreakIndent,
                        if (trailingDereferences) expressionBreakIndent else ZERO
                    )
                    .foo()
```

**Comment by strulovich** [comment]
Your last example is how we expect things to be. How would you expect it to look?

(The double indent for arguments is to separate them visually from the rest of the chain.

**Comment by att14** [comment]
I was a little confused that adding a chain changed the indentation of the previous statement. I would expect it to look like this, since the trailing `)` is what visually separates the parameters from the chain.

```
val argsIndent =
                Indent.If.make(
                    nameTag,
                    expressionBreakIndent,
                    if (trailingDereferences) expressionBreakIndent else ZERO
                )
                    .foo()
```

If this is expected, then feel free to close.

**Comment by strulovich** [comment]
Yeah, this is expected, it's about avoiding "floating" in the chaining (so keep the closing parenthesis with the next .) and avoid confusing args with the next parts of the chain.

This is taken from Google-Java-Format's behaviors which outputs:
```
    Indent.If.make(
            nameTag, expressionBreakIndent, trailingDereferences ? expressionBreakIndent : ZERO)
        .foo();
 ```
