### ISSUE TITLE
Support Kotlin 1.7.0's rangeTo operator

### ISSUE THREAD

**Issue by ZacSweers** [facebookincubator/ktfmt#333]
Kotlin 1.7.0 introduced a new `..` operator that can be used in place of `until`. https://kotlinlang.org/docs/ranges.html

<img width="771" alt="image" src="https://user-images.githubusercontent.com/1361086/176516244-c0e4c5e2-fa3d-4a8f-8dba-12932df18001.png">

Example:

```kotlin
for (i in 0..9) {

}

// Previously
for (i in 0 until 10) {

}
```

Currently this fails to format in 0.39

```
Execution failed for task ':app:spotlessKotlin'.
--
  | > 236:41: error: Expecting an expression
```

**Comment by JavierSegoviaCordoba** [comment]
That isn't the new operator, the new one is something like `..<` but I can't find it in the 1.7.0 release notes.

I have used the `..` operator with no issues in the past, so I am not sure if this is a bug in a new ktfmt version.

**Comment by ZacSweers** [comment]
Ahh sorry you're correct
