### ISSUE TITLE
Kotlin script files (.kts)

### ISSUE THREAD

**Issue by russellw** [facebookincubator/ktfmt#35]
ktfmt looks good so far! Only deficiency I have found is that it doesn't work on script (.kts) files. Any chance of adding this?

**Comment by cgrushko** [comment]
Looks like `ktfmt` is parsing the file as if it were a `.kt` file, expecting a top-level declaration.

```
$ cat > ~/temp/foo.kts
println("Called with args:")
args.forEach {
    println("- $it")
}

$ java -jar ktfmt-0.13-SNAPSHOT-jar-with-dependencies.jar ~/temp/foo.kts
~/temp/foo.kts:1:1: error: Expecting a top level declaration
```

Something inside `Parser.kt` causes `kotlin-compiler` to expect a `.kt` file instead of ` .kts`. 
`KotlinFileType.INSTANCE` looks suspicious, but there's no `kts` equivalent.

**Comment by cgrushko** [comment]
Had to rollback the changes that added support for scripts, so reopening.

**Comment by jdemeulenaere** [comment]
Are there any news regarding support for Kotlin Script files? It would be very useful to us as we are currently using ktlint but we would like to migrate to ktfmt for both normal and script Kotlin files.

**Comment by cgrushko** [comment]
@jdemeulenaere  glad you find ktfmt useful :) 
Script support was added in https://github.com/facebookincubator/ktfmt/commit/c2cf421af2365aaa8c7e3cef358641559d127384, but unfortunately had to be rolled back because it hurt preserving some newlines, as well as newlines between `package` and the rest of the file when there are no imports. We'll get to it soon-ish, I hope.

**Comment by cgrushko** [comment]
There's now preliminary support in the main branch. It'll do undesirable things like surrounding every statement in newlines, but at least it ktfmt no longer chokes on kts files.

**Comment by JavierSegoviaCordoba** [comment]
Is there a snapshot for it?

**Comment by cgrushko** [comment]
I uploaded a snapshot to 
```
<dependency>
  <groupId>com.facebook</groupId>
  <artifactId>ktfmt</artifactId>
  <version>0.20-SNAPSHOT</version>
</dependency>
```

see https://stackoverflow.com/questions/7715321/how-to-download-snapshot-version-from-maven-snapshot-repository for hwo to add the OSSRH snapshot repo to your Maven repo list.

**Comment by MathieuLorber** [comment]
Hi, everything seems to be ok now, with just a small problem : formatting scripts starting by a hashbang will fail
`#!/usr/bin/env kscript`
Is there any chance to support it ?

**Comment by ZacSweers** [comment]
@cgrushko would you be open to a PR for the hashbang support via just peeking the first line and skipping it if it is a hashbang?

**Comment by cgrushko** [comment]
@ZacSweers was just implemented in https://github.com/facebookincubator/ktfmt/commit/d71487b6c76b23a5b4c580185c9e48f3694f0b96 :) next weekly release should pick it up.
