### ISSUE TITLE
Random breaking line on function parenthesis with no params (Ktfmt version `0.40`)

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [facebookincubator/ktfmt#353]
There are ugly break lines on some chain functions as you can see on that `.trimMargin()`.

@nreid260 I think there is a missing test for this use case in some of the chain functions PRs that were merged some months ago.

```kotlin
try {
    // ...
} catch (e: Exception) {
    println(
        """
           | # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
           | # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
           | # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
        """.trimMargin(
        )
    )
    // ...
}
```

**Comment by nreid260** [comment]
This is fixed at head.

**Comment by JavierSegoviaCordoba** [comment]
![image](https://user-images.githubusercontent.com/7463564/192114597-9c4733a9-0b93-420d-bd49-d577f685f46e.png)
@nreid260 is it expected that change and now it is "floating"?
