### ISSUE TITLE
Removal of braces around single-line statements

### ISSUE THREAD

**Issue by russellw** [facebookincubator/ktfmt#40]
Another source of entropy that currently needs to be cleaned up by hand is braces around single-line statements. Any chance of making ktfmt remove these?

**Comment by cgrushko** [comment]
We've actually debated whether ktfmt should be doing this (regardless of the technical challenges of adding/removing non-whitespace).
I personally feel it's too intrusive for a formatter to remove braces under a developer's feet. Let's see what others think.

**Comment by cgrushko** [comment]
I'll elaborate on my thoughts -
Unlike semi-colons, which are never necessary, empty blocks are sometimes a result of work-in-progress. I would find it annoying if I'd start writing a function, hit save which would trigger auto-format, which would delete my empty block.

**Comment by russellw** [comment]
Okay, that's a fair argument. My workflow is different – I use ktfmt from
the command line when I'm ready to commit a change – but if some people are
using it with save and autoformat, then yes, I can see how removing
redundant braces would be a problem.
