### ISSUE TITLE
`ktfmt` chokes on files with CRLF line breaks

### ISSUE THREAD

**Issue by russellw** [facebookincubator/ktfmt#41]
I just tried ktfmt on the simplest possible correct Kotlin program:

fun main(){
    println("test")
}

And was unpleasantly surprised when it failed:

C:\ayane>java -jar \bin\ktfmt-0.13-jar-with-dependencies.jar main.kt
main.kt:1:12: error: Expecting an element

This is the same version, and indeed copy, of ktfmt that the other day was successfully formatting a much more complex program. Any idea what's wrong here?

**Comment by cgrushko** [comment]
Interesting. I can't reproduce this using a very similar command line on a mac. (I didn't test it on Windows, I'm glad it works fine, usually).

1/ Can you post a hexdump of your file, so I'm sure I have exactly the same file?

This is what I have:
```
$ cat main.kt
fun main(){
println("test")
}
$ hexdump main.kt
0000000 66 75 6e 20 6d 61 69 6e 28 29 7b 0a 70 72 69 6e
0000010 74 6c 6e 28 22 74 65 73 74 22 29 0a 7d 0a
000001e
```

2/ And to be sure, the extension is .kt, right?
3/ Is this the minimal repro? can you remove the println and keep it failing?

**Comment by russellw** [comment]
Aha! that's it: it works if you are using UNIX line endings. It so happened
that the file I was trying it with, had been saved with DOS line endings
(CR LF). Okay so that's a workaround for the moment: always use UNIX line
endings even on Windows.

**Comment by cgrushko** [comment]
Weird; this means that kotlin-compiler chokes on CRLF? does IntelliJ not produce CRLF under certain circumstances?

Anyway, sounds like we can fix it by converting CRLF (and CR) to LF before feeding it to kotlin-compiler. IIRC google-java-format's engine (which ktfmt is using) will produce only LF anyway.

Is this something you'd like to try to tackle?

**Comment by arturbosch** [comment]
You could use `org.jetbrains.kotlin.com.intellij.openapi.util.text.StringUtilRt.convertLineSeparators(content)` to normalize the content before parsing it to a `KtFile`.

**Comment by russellw** [comment]
Kotlin compiler has no trouble with CRLF, which is why I was confused; the
program was compiling just fine. IntelliJ on Windows does produce CRLF
unless you explicitly set it not to (which I have now done).

**Comment by cgrushko** [comment]
My guess is that “kotlinc” is not the same as the maven package
“kotlin-compiler”; the former could be canonicalizing the input before
passing it to the actual compiler, similarly to what @arturbosch was
suggesting.
