### ISSUE TITLE
`dynamic` return type not supported

### ISSUE THREAD

**Issue by nunocastromartins** [facebookincubator/ktfmt#49]
Example code:
```kt
fun x(): dynamic = "x"
```

Errors out with:
```
> 1:10: error: expected token: 'dynamic'; generated = instead
```

**Comment by cgrushko** [comment]
I sent out an internal diff to fix it, will probably take until Monday for it to be merged upstream.
I created a dummy PR with the fix in case you'd like to build from source: https://github.com/facebookincubator/ktfmt/pull/50
