### ISSUE TITLE
Kotlin 1.4 support

### ISSUE THREAD

**Issue by ZacSweers** [facebookincubator/ktfmt#59]
Presumably this will require updates to support new language features like `fun interface` and trailing commas?

**Comment by cgrushko** [comment]
1. Trailing commas are already supported
2. I skimmed https://blog.jetbrains.com/kotlin/2019/12/what-to-expect-in-kotlin-1-4-and-beyond/, and seems that most new things should already work.
3. `fun interface` might actually work out of the box, depending on how it's represented in the AST. If not, it should be a trivial amount of work.

Question - do you happen to have a list of snippets where `ktfmt` fails? Having them in the format of unit-tests in [FormatterKtTest.kt](https://github.com/facebookincubator/ktfmt/blob/master/core/src/test/java/com/facebook/ktfmt/FormatterKtTest.kt) would be wonderful :)

**Comment by ramonsaboya** [comment]
@cgrushko snippet of `ktfmt` failure for `fun interface`:
```kotlin
public fun interface PacketHandlerFunction<T : Packet<*>> : (Player, T?) -> T?
```

I'm getting the error:
```
33:11: error: Expecting function name or receiver type
com.facebook.ktfmt.ParseError: 33:11: error: Expecting function name or receiver type
```

**Comment by cgrushko** [comment]
Yeah, we need to at least upgrade the parser to 1.4. 
I have a draft diff with the changes required to ugprade to 1.4, I'll get to it soon-ish.

**Comment by jackmahoney** [comment]
Much appreciate your work. Thanks

**Comment by CrushedPixel** [comment]
Any update on this?

**Comment by jackmahoney** [comment]
@cgrushko do you possibly have the update for this? If you want to open a work in progress pull request maybe I can help?

**Comment by cgrushko** [comment]
Apologies for the delay - we're still on 1.3 internally, and I was hoping we'll get to 1.4 any day. 
Because we build internally inside a monorepo, we need to make special arrangement to build both for 1.3 and for 1.4.
As I said, I was hoping I can get away with waiting a bit.

The problem is that Kotlin's interface of the visitor has changed in a backwards incompatible way.

Let me see if I can whip up something using reflection.

**Comment by cgrushko** [comment]
Almost got it to work: https://github.com/facebookincubator/ktfmt/pull/68

I can't figure out how to tell Maven _not_ to compile `Kotlin13InputAstVisitor.kt`, so one must first delete this file before compiling.

**Comment by JavierSegoviaCordoba** [comment]
@cgrushko do you think the new version will be available this week? I am going to start a new project and I would like to test it there to get some conclusions before presenting it to my partners so we can use it over ktlint or detekt

**Comment by cgrushko** [comment]
Yes, I expect we'll figure it out soon.

**Comment by cgrushko** [comment]
Let me release a new version.

**Comment by JavierSegoviaCordoba** [comment]
I am checking maven central and I don't find it. Is it in a snapshot repository so I can start testing it?

**Comment by cgrushko** [comment]
@JavierSegoviaCordoba, I finally got around to it. There's a link to Maven Central from https://github.com/facebookincubator/ktfmt/releases/tag/v0.19 .

**Comment by JavierSegoviaCordoba** [comment]
Thank you very much :)

**Comment by JavierSegoviaCordoba** [comment]
@cgrushko The IntelliJ plugin has to be updated to get the last version? I checked the code and I see it is using `val ktfmtVersion = "0.18"`

I don't know if there is a way that let you avoid the usage of it directly in the project and adding a spinner menu with al the current versions available in MavenCentral. If you think it is possible I can file a new issue to ask this there as a feature request.

**Comment by cgrushko** [comment]
Ugh, the AS plugin is a problem we didn't figure out yet. I think what you suggest makes total sense, and is much better than releasing a plugin every time AS or ktfmt changes, but doing this is probably more complicated (unless IntelliJ plugins have access to such capability from the platform?)

The underlying is reason is of course that we have our own in-house plugin, so we don't dogfood this.
