### ISSUE TITLE
Breaks inserted into middle of return type

### ISSUE THREAD

**Issue by sgrimm** [facebookincubator/ktfmt#6]
I have an interface with a function whose return value has type arguments, and ktfmt breaks the type arguments across multiple lines. This seems to violate the "prefer to break at a higher semantic level" approach of google-java-format.

Original:

```kotlin
interface X {
  fun functionWithGenericReturnType(
    arg1: Arg1Type, arg2: Arg2Type
  ): Map<String, Map<String, Double>>?
}
```

ktfmt output:

```kotlin
interface X {
  fun functionWithGenericReturnType(arg1: Arg1Type, arg2: Arg2Type): Map<
      String,
      Map<String, Double>>?
}
```

I would have expected it to reformat to something like my original formatting, or perhaps put each argument on a separate line, such that `Map<String, Map<String, Double>>?` would be treated as a single semantic unit and kept on the same line.

**Comment by cgrushko** [comment]
1. Thanks for the detailed repro!
2. I published https://github.com/facebookincubator/ktfmt/pull/8, let me know what you think of the result. We'll have to wait for someone to review it, which will probably only happen after the holidays.

**Comment by hick209** [comment]
PR #8 reviewed 😉

**Comment by sgrimm** [comment]
Looks better now! Thanks.
