### ISSUE TITLE
Markdown lists not preserved in KDoc comments

### ISSUE THREAD

**Issue by sgrimm** [facebookincubator/ktfmt#7]
ktfmt does not recognize Markdown list syntax in KDoc comments, and concatenates them into a single paragraph. Both numbered and bulleted lists are affected.

Input:

```kotlin
/**
 * This function does a couple things.
 *
 * 1. Demonstrates Markdown list formatting. 
 * 2. Demonstrates ktfmt reformatting.
 */ 
fun commentFormatTest() {}
```

ktfmt output:

```kotlin
/**
 * This function does a couple things.
 *
 * 1. Demonstrates Markdown list formatting. 2. Demonstrates ktfmt reformatting.
 */
fun commentFormatTest() {}
```

**Comment by cgrushko** [comment]
1. Thanks for the repro!
2. Current workaround: use <pre> tags, same as in Javadoc.
3. The root cause is that we're using google-java-format's Javadoc formatter (I made a small change to avoid emitting <p> tags). https://github.com/facebookincubator/ktfmt/blob/master/core/src/main/java/com/facebook/ktfmt/kdoc/KDocFormatter.java . We'll get much better results once we switch to using Kotlin Compiler for comments. (for example, `KDocTokens` mentions Markdown). We'll get to it eventually.

**Comment by strulovich** [comment]
This is not a long term solution, but this commit minimizes this issue for now:

https://github.com/facebookincubator/ktfmt/commit/44229c28dd3b1f284b568d931eb116fd9313fb2e

Long term we would like to get KDoc formatting properly done, and I will keep looking into that.

**Comment by sgrimm** [comment]
Thanks! Out of curiosity, would it work to pass the documentation contents through [Flexmark](https://github.com/vsch/flexmark-java) configured to render to Markdown with the appropriate line length?

**Comment by strulovich** [comment]
Opened https://github.com/facebookincubator/ktfmt/issues/15 to keep track of the larger goal of getting proper formatting.

**Comment by strulovich** [comment]
@sgrimm - I'll look into that, but @cgrushko pointed out that kotlinc might be parsing the AST of KDoc anyhow, in which case I think I'll prefer using that dependency.

**Comment by strulovich** [comment]
I think this is fixed by adding better parsing for KDocs.

Here is an example test:
https://github.com/facebookincubator/ktfmt/blob/c8b7b31f77d786f4c2b3ab622a1b93cea6561831/core/src/test/java/com/facebook/ktfmt/FormatterKtTest.kt#L875

Anything else missing here @sgrimm?

**Comment by sgrimm** [comment]
I think that test covers it pretty well, and it's definitely way better now than it was when I filed this issue. I'm not sure it's doing the right thing when it wraps list items onto multiple lines, though. It will change

    - a b c d e f g

to

    - a b c d
    e f g

but for the second line to be considered part of the list item, I believe the indentation has to match the first line, like

    - a b c d
      e f g

**Comment by strulovich** [comment]
My go to is looking at the quick documentation feature in Android studio.
Looking at:
```
  /**
   * This is a list:
   * - item 1 
   * what now
   * - item 2
   */
  private fun foo() {}
```

By selecting the function and choosing "quick documentation" I see Android Studio considers these to be the same item in the list:
![image](https://user-images.githubusercontent.com/4662781/81758981-5d050400-9491-11ea-9cb5-09840d6d4538.png)

**Comment by sgrimm** [comment]
Ah, you are absolutely right! This looks good, then. Thanks!
