### ISSUE TITLE
Add IntelliJ, Android Studio, and other JetBrains IDEs plugins for ktfmt

### ISSUE THREAD

**Issue by ujjwalagrawal17** [facebookincubator/ktfmt#9]
Add IntelliJ, Android Studio, and other JetBrains IDEs plugins

**Comment by cgrushko** [comment]
1. Thanks!
2. This is indeed on our high-priority list. We'll give this more attention once everybody in the US is back from the holidays.
3. Superficially, this seems like a matter of forking https://github.com/google/google-java-format/tree/master/idea_plugin and changing GJF classes to ktfmt's. (although, ktfmt doesn't support all options that GJF supports, which is another matter).

**Comment by ujjwalagrawal17** [comment]
Can someone from your team fork the repo. I will like to contribute to it if possible. Thanks.

**Comment by cgrushko** [comment]
@ujjwalagrawal17 by forking, I meant copying https://github.com/google/google-java-format/tree/master/idea_plugin into https://github.com/facebookincubator/ktfmt/ and making changes (and adding some comments explaining the changes). We'll get to it once the holidays are over, as I mentioned. Feel free to experiment with this in the meantime.

**Comment by jef** [comment]
Has there been any progress on this? I might want to look into converting this, but don't want to step over someone else's progress.

**Comment by cgrushko** [comment]
@jef please do :) I didn't get around to it yet... 
Thanks!

**Comment by jef** [comment]
I started working on this, but quickly got overwhelmed with what I actually wanted to do. I'm not sure if we wanted to convert the Java into Kotlin as well as setup for ktfmt.

My knowledge ends where the formatting begins, so it'll have to be something I sit down for a couple hours to understand the google format plugin before tackling this again.

Not sure if you started any progress, but I also don't know how soon I can get to it. I'll see if I can carve in some time again in the near future to do the above.

**Comment by cgrushko** [comment]
I would go for keeping everything Java (as well as keeping the copyright headers) and just copying it all and modifying the minimum required to get ktfmt working in IntelliJ.

I haven't gotten around to it yet; I might have time in the coming weeks. I'll update here if I start working on this.

**Comment by cgrushko** [comment]
Summary of my invetigation:
1. I have a diff that creates such plugin.
2. It requires ktfmt to switch to using kotlin-compiler-embeddable (instead of kotlin-compiler) because of class conflicts. However, kotlin-compiler-embeddable is missing JNA, which crashes ktfmt on Java 8, which is a blocker for Facebook. (https://youtrack.jetbrains.com/issue/KT-40937). I'll try to figure out which JNA is being used there and add it to ktfmt and try again.

**Comment by tyvsmith** [comment]
When I was playing with GraalVM native-image and had swapped it to the embeddable compiler, I ran into the JNA issue as well, and ended up just plugging in jna-5.5.0.jar from artifactory into the classpath, to pass. I ended up running into other blockers so never could determine other side effects, but should be reasonable to put whatever is needed on the classpath though.

**Comment by cgrushko** [comment]
I used jna-4.2.2 and it seems to be working (https://github.com/facebookincubator/ktfmt/commit/4343c1a97c49abd16ec0cef1106ed6d4634a53d5).
Haven't released it yet.
